sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t travis_test .

scripts:
  - docker run -e CI=true travis_test npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react
  env: DockerReact-env
  bucket_name: $AWS_BUCKET
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
